version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: url-shortener-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-url_service}
    ports:
      - "${DB_PORT:-5435}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migration:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - url-shortener-network

  url-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-service
    ports:
      - "${SERVER_PORT:-8080}:8080"
      - "${HTTP_PORT:-8081}:8081"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-url_service}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - url-shortener-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  url-shortener-network:
    driver: bridge
