database:
  host: localhost
  port: 5435
  user: postgres
  password: postgres
  dbname: url_service
  sslmode: disable
  max_connections: 10
  max_idle_connections: 5

server:
  port: 8080
  host: 0.0.0.0
